---
version: '2.2'

networks:
  default:
    external:
      name: sodas

services:
  sodas.zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: sodas.zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  sodas.broker:
    image: confluentinc/cp-kafka
    container_name: sodas.broker
    depends_on:
      - sodas.zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: sodas.zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sodas.broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_EXTERNAL_PORT: 9093